version: 2.1
orbs:
  slack: circleci/slack@4.1
  jira: circleci/jira@2.1.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      # Replace Netlify deployment with S3 deployment
      - run:
          name: Deploy to S3
          command: |
            sudo apt-get -y update && sudo apt-get install -y awscli
            aws s3 sync ./build s3://ibrahim-react-js-test --delete
      - run:
          name: Extract Jira issue key
          command: |
            set -x
            echo "start"
            COMMIT_MESSAGE=$(git log -10 --pretty=%B)
            ISSUE_KEY=$(echo $COMMIT_MESSAGE | grep -o 'NAR-[0-9]\+')
            echo 'export ISSUE_KEY="$ISSUE_KEY"' >> $BASH_ENV
            echo "ISSUE_KEY $ISSUE_KEY"
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
      - slack/notify:
          channel: C1MDAQGBS
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C1MDAQGBS
          event: pass
          template: success_tagged_deploy_1
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm test
      - slack/notify:
          channel: C1MDAQGBS
          event: fail
          custom: |  
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Test Failure",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "@here $CIRCLE_BRANCH The Test has *failed*. Please check the CircleCI logs for more details."
                    }
                  ]
                }
              ]
            }
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - staging
                - /sprint-.*/
      - test:
          filters:
            branches:
              only:
                - /sprint-.*/


# Define the basic_fail_1 template
templates:
  basic_fail_1:
    format: |
      {
        "blocks": [
           {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "Buil Failure",
              "emoji": true
            }
          },
          {
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "@here The build has *failed*. Please check the CircleCI logs for more details."
              }
            ]
          }
        ]
      }