version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm testt
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      # Replace Netlify deployment with S3 deployment
      - run:
          name: Deploy to S3
          command: |
            sudo apt-get -y update && sudo apt-get install -y awscli
            aws s3 sync ./build s3://ibrahim-react-js-test --delete
      - slack/notify:
          channel: C1MDAQGBS
          event: pass
          template: basic_success
      - slack/notify:
          channel: C1MDAQGBS
          event: fail
          template: basic_fail_1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - staging


# Define the basic_fail_1 template
templates:
  basic_success:
    format: |
      {
        "blocks": [
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "Bariatric Web",
              "emoji": true
            }
          },
          {
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "@here New release deployed"
              }
            ]
          }
        ]
      }
  basic_fail_1:
    format: |
      {
        "blocks": [
           {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "Buil Failure",
              "emoji": true
            }
          },
          {
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "@here The build has *failed*. Please check the CircleCI logs for more details."
              }
            ]
          }
        ]
      }